---
output:
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
geometry: margin=1in

author: Avritt Rohwer
fontawesome: yes
phone: "616 295 1175"
email: avritt.rohwer@gmail.com
github: avrittrohwer
web: avrittrohwer.com

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

\thispagestyle{empty}

# Relevant skills \hrulefill

- Systems level software development in C, specifically in a Linux environment.
- Full stack web development, isomorphic JavaScript, product development.

# Experience \hrulefill

**IS Intern** \hfill May 2018 - January 2019

*Warner Norcross + Judd LLP, Grand Rapids MI*

- Prototyped and developed an internal web application that streamlined the sales pipeline.
- Integrated the sales pipeline into existing legacy services and workflows.

**Helpdesk Intern** \hfill September 2016 - December 2017

*REMC 1, Houghton MI*

- Provided technical help-desk services by phone, email, online chat, and occasionally directly
  on-site to dozens of school districts.
- Packaged and deployed software to thousands of computers.

**Shift Manager, Barista** \hfill June 2014 - August 2016

*Biggby Coffee, Grand Rapids MI*

- Provided valued customer service, testimonial available upon request.
- Quickly advanced to a shift manager after only a few months of work.


# Education \hrulefill

**BS, Computer Science; Minor, Mathematical Sciences** \hfill September 2016 - current

*Michigan Technological University, Houghton MI*

- GPA: 3.11
- Expected Graduation: May 2019.
- Awarded a Certificate of Merit for Outstanding Academic Achievements in *Introduction to Coding 
  Theory*

**High School** \hfill September 2012 - June 2016

*Northview High School, Grand Rapids MI*

- GPA: 4.1, *summa cum laude*.

# Interests \hrulefill

- Skiing, backpacking, fishing.
- Functional programming paradigm.
- Hacking away at my dotfiles.

\vspace*{\fill}
\begin{center}
References available upon request.
\end{center}
