---
output:
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
geometry: margin=1in

author: Avritt Rohwer
fontawesome: yes
phone: "616 295 1175"
email: avritt.rohwer@gmail.com
github: avrittrohwer
web: avrittrohwer.com

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

\pagenumbering{gobble}
\thispagestyle{empty}

# In my work, I strive to:

- Implement simple solutions that are easy to understand and maintain.
- Define success metrics before beginning implementation.
- Achieve impact with concise, iterative deliverables.
- Treat documentation as a first-class engineering artifact.

# Experience \hrulefill

**Software Engineer** \hfill September 2022 - March 2023

*Google.org Fellow, CiviForm*

- Led enhancements to the [CiviForm cloud deployment
  tool](https://docs.civiform.us/it-manual/sre-playbook/terraform-deploy-system).
  Wrote a [6 month roadmap and delivery
  plan](https://docs.google.com/document/d/1DgKX1uSFHOJooSsBRoefc1VhNIKCBwKHg6ZrGys84cM/edit?usp=sharing)
  to guide my time.
- Helped ensure a successful launch in the state of Arkansas. Collaborated with
  state IT administrators to fix deployment issues and ensure CiviForm
  integrated into their infrastructure.
- Designed and implemented the [pgadmin
  command](https://docs.civiform.us/it-manual/sre-playbook/terraform-deploy-system#aws)
  allowing for temporary database access via a [web
  UI](https://www.pgadmin.org/).
- Designed and implemented [end-to-end
  testing](https://docs.google.com/document/d/1y1IFnuorFIsGJggMwJdLgAHtGMGPr9XDd8AdXH5VAlw/edit?usp=sharing)
  of the cloud deployment tool.
- Designed and implemented [documentation
  generation](https://docs.google.com/document/d/1jYNeMqa9qK40JhPrtvNehzl-ooBeqQlnbZif2HvhuKw/edit?usp=sharing)
  for all environment variables the CiviForm server reads from. Added a GitHub
  action that ensures any added environment variables have corresponding
  documentation.

**Software Engineer** \hfill September 2019 - August 2022

*Google Kubernetes Engine, Kubernetes Control Plane team*

- Designed and implemented a Kubernetes Control Plane VM bootstrap success rate
  SLI and SLO. Designed and implemented logs observability pipeline and fleet
  analytics tooling. Utilized tooling to identify 15 unique failure modes, 6 of
  which were proactively caught via SLO alerts. Implemented or delegated
  mitigations as appropriate, achieving consistent per-minor-version,
  per-location 99.9% success rate.
- Designed and implemented an oncall ticket responder that provides useful
  debugging context. Delivered highest-priority functionality for my team,
  reducing our alert median-time-to-resolution by 18 hours. Wrote a design to
  make the responder usable and extendable by other teams. The design was
  implemented by another team who used it reduce their customer issue
  mean-time-to-resolution by 5 days. The responder is used by 6 teams.
- Wrote and maintained a fleet analysis Colab (Jupyter notebook) template.
  Utilized tooling to identify impact of 8 production issues. Facilitated and
  led 3 team training sessions on data analysis in GKE.
- Collaborated with our customer support organization to reduce toil. Proposed
  a streamlined customer outreach process for our team which has saved 100+
  extraneous tickets from being created. Wrote playbooks enabling support to
  run common mitigation commands which has saved 6 customer issues from being
  escalated to our team.
- Designed a ramp-up project for a new engineer joining
  the team. Provided one-on-one mentorship enabling successful and timely
  implementation.

**IS Intern** \hfill May 2018 - January 2019

*Warner Norcross + Judd LLP, Grand Rapids MI*

- Prototyped and developed an internal web application that streamlined the sales pipeline.
- Integrated the sales pipeline into existing legacy services and workflows.

\pagebreak

**Helpdesk Intern** \hfill September 2016 - December 2017

*REMC 1, Houghton MI*

- Provided technical help-desk services by phone, email, online chat, and occasionally directly
  on-site to dozens of school districts.
- Packaged and deployed software to thousands of computers.

# Education \hrulefill

**BS, Computer Science; minor, Mathematical Sciences** \hfill September 2016 - May 2019

*Michigan Technological University, Houghton MI*

- GPA: 3.20.
- Awarded a Certificate of Merit for Outstanding Academic Achievement in *Introduction to Coding
  Theory*.
